// LuxTalent V2 - Mock Data (development only)
// In production, all data comes from the Flask API

import type {
  HealthResponse,
  PredictionResponse,
  FairnessMetricsResponse,
  ScreeningLogEntry,
  FairnessTrendPoint,
  ParseResponse,
  ExplainResponse,
} from './types';

export const MOCK_HEALTH: HealthResponse = {
  status: 'ok',
  model_ready: true,
  model_name: 'Logistic Regression (C=0.5, l2)',
  fairness_enabled: true,
  version: 'V2',
};

export const MOCK_PREDICTION: PredictionResponse = {
  name: 'Marie Dupont',
  target_role: 'Senior Data Analyst',
  stage: 'ml_model',
  passed: true,
  label: 'Invite',
  confidence: 78.5,
  probabilities: { Invite: 78.5, Reject: 21.5 },
  model_name: 'Logistic Regression (C=0.5, l2)',
  fairness_adjusted: true,
  version: 'V2',
  features: {
    age: 36,
    years_experience: 12.0,
    education_level: 4,
    nb_certifications: 2,
    nb_extra_languages: 2,
    nb_extra_skills: 6,
    has_management_experience: 1,
    has_international_experience: 1,
    gender: 0,
  },
  explanation: {
    base_value: -0.8234,
    shap_values: {
      Age: 0.0521,
      'Years of Experience': 0.4512,
      'Education Level': 0.2301,
      Certifications: 0.1023,
      'Extra Languages': 0.0834,
      'Extra Skills': 0.0612,
      'Management Experience': 0.1923,
      'International Experience': 0.1432,
    },
    top_features: [
      ['Years of Experience', 0.4512],
      ['Education Level', 0.2301],
      ['Management Experience', 0.1923],
    ],
    decision_drivers:
      "Les principaux facteurs de cette décision sont : Années d'expérience (+0.45, fortement en faveur de Invite), Niveau d'éducation (+0.23, modérément en faveur de Invite), et Expérience de management (+0.19, modérément en faveur de Invite).",
  },
};

export const MOCK_REJECT_PREDICTION: PredictionResponse = {
  name: 'Thomas Bernard',
  target_role: 'Senior Data Analyst',
  stage: 'ml_model',
  passed: false,
  label: 'Reject',
  confidence: 68.3,
  probabilities: { Invite: 31.7, Reject: 68.3 },
  model_name: 'Logistic Regression (C=0.5, l2)',
  fairness_adjusted: true,
  version: 'V2',
  features: {
    age: 24,
    years_experience: 2.0,
    education_level: 3,
    nb_certifications: 0,
    nb_extra_languages: 1,
    nb_extra_skills: 3,
    has_management_experience: 0,
    has_international_experience: 0,
    gender: 1,
  },
  explanation: {
    base_value: -0.8234,
    shap_values: {
      Age: -0.1203,
      'Years of Experience': -0.3845,
      'Education Level': 0.0512,
      Certifications: -0.0891,
      'Extra Languages': 0.0234,
      'Extra Skills': -0.0145,
      'Management Experience': -0.1523,
      'International Experience': -0.1102,
    },
    top_features: [
      ['Years of Experience', -0.3845],
      ['Management Experience', -0.1523],
      ['International Experience', -0.1102],
    ],
    decision_drivers:
      "Les principaux facteurs de cette décision sont : Années d'expérience (-0.38, fortement en faveur de Reject), Expérience de management (-0.15, modérément en faveur de Reject), et Expérience internationale (-0.11, modérément en faveur de Reject).",
  },
};

export const MOCK_FAIRNESS_METRICS: FairnessMetricsResponse = {
  version: 'V2',
  fairness_constraint: 'equalized_odds',
  base_model: {
    epd: 8.3,
    epd_alert: true,
    rid: 0.789,
    rid_alert: true,
    delta_tpr: 4.2,
    delta_tpr_alert: false,
    group_stats: {
      Male: { n: 45, invite_rate: 42.2, tpr: 60.0, fpr: 25.0 },
      Female: { n: 35, invite_rate: 33.9, tpr: 55.0, fpr: 20.0 },
    },
  },
  fair_model: {
    epd: 2.1,
    epd_alert: false,
    rid: 0.956,
    rid_alert: false,
    delta_tpr: 1.3,
    delta_tpr_alert: false,
    group_stats: {
      Male: { n: 45, invite_rate: 37.8, tpr: 58.0, fpr: 22.0 },
      Female: { n: 35, invite_rate: 35.7, tpr: 57.0, fpr: 21.0 },
    },
  },
  performance_comparison: {
    base: { accuracy: 0.66, f1_invite: 0.46, f1_reject: 0.76, auc: 0.72 },
    fair: { accuracy: 0.64, f1_invite: 0.43, f1_reject: 0.74 },
  },
  proxy_analysis: [
    { feature: 'age', pearson_r: 0.1245, pearson_pval: 0.234, mutual_info: 0.0234, is_proxy: false },
    { feature: 'years_experience', pearson_r: 0.0832, pearson_pval: 0.412, mutual_info: 0.0156, is_proxy: false },
    { feature: 'education_level', pearson_r: -0.0523, pearson_pval: 0.621, mutual_info: 0.0089, is_proxy: false },
    { feature: 'nb_certifications', pearson_r: 0.2103, pearson_pval: 0.089, mutual_info: 0.0312, is_proxy: false },
    { feature: 'nb_extra_languages', pearson_r: -0.1456, pearson_pval: 0.178, mutual_info: 0.0198, is_proxy: false },
    { feature: 'nb_extra_skills', pearson_r: 0.3521, pearson_pval: 0.012, mutual_info: 0.0467, is_proxy: true },
    { feature: 'has_management_experience', pearson_r: 0.2678, pearson_pval: 0.045, mutual_info: 0.0345, is_proxy: false },
    { feature: 'has_international_experience', pearson_r: 0.0891, pearson_pval: 0.398, mutual_info: 0.0123, is_proxy: false },
  ],
};

export const MOCK_SCREENING_LOG: ScreeningLogEntry[] = [
  {
    timestamp: '2026-05-14T13:55:19',
    filename: 'cv1.txt',
    name: 'Olivia Martinez',
    target_role: 'Senior Data Analyst',
    stage: 'ml_model',
    label: 'Invite',
    confidence: 90.6,
    model_name: 'Logistic Regression (C=1.0, l1)',
    fairness_adjusted: true,
    top_driver: 'Years of Experience (+0.45)',
    reasons: '',
    status: 'Entretien planifié',
  },
  {
    timestamp: '2026-05-14T13:55:19',
    filename: 'cv2.txt',
    name: 'Marcus Liu',
    target_role: 'Operations Manager',
    stage: 'ml_model',
    label: 'Invite',
    confidence: 95.1,
    model_name: 'Logistic Regression (C=1.0, l1)',
    fairness_adjusted: false,
    top_driver: 'Management Experience (+0.38)',
    reasons: '',
    status: 'Embauché',
  },
  {
    timestamp: '2026-05-14T13:55:19',
    filename: 'cv3.txt',
    name: 'Hannah Schneider',
    target_role: 'Software Engineering Lead',
    stage: 'ml_model',
    label: 'Invite',
    confidence: 80.3,
    model_name: 'Logistic Regression (C=1.0, l1)',
    fairness_adjusted: true,
    top_driver: 'Education Level (+0.31)',
    reasons: '',
    status: 'En attente',
  },
  {
    timestamp: '2026-05-14T13:55:19',
    filename: 'cv4.txt',
    name: 'Daniel Okafor',
    target_role: 'Financial Controller',
    stage: 'ml_model',
    label: 'Invite',
    confidence: 98.1,
    model_name: 'Logistic Regression (C=1.0, l1)',
    fairness_adjusted: false,
    top_driver: 'Years of Experience (+0.52)',
    reasons: '',
    status: 'Entretien planifié',
  },
  {
    timestamp: '2026-05-14T13:55:24',
    filename: 'cv5.txt',
    name: 'Sophie Dubois',
    target_role: 'Marketing Manager',
    stage: 'ml_model',
    label: 'Invite',
    confidence: 64.8,
    model_name: 'Logistic Regression (C=1.0, l1)',
    fairness_adjusted: true,
    top_driver: 'International Experience (+0.21)',
    reasons: '',
    status: 'En attente',
  },
  {
    timestamp: '2026-05-14T12:30:10',
    filename: 'cv6.txt',
    name: 'Pierre Leclerc',
    target_role: 'Junior Analyst',
    stage: 'ml_model',
    label: 'Reject',
    confidence: 72.4,
    model_name: 'Logistic Regression (C=0.5, l2)',
    fairness_adjusted: true,
    top_driver: 'Years of Experience (-0.29)',
    reasons: 'Insufficient experience',
    status: 'Refusé',
  },
  {
    timestamp: '2026-05-14T12:30:10',
    filename: 'cv7.txt',
    name: 'Anna Kowalski',
    target_role: 'Senior Data Analyst',
    stage: 'ml_model',
    label: 'Reject',
    confidence: 58.9,
    model_name: 'Logistic Regression (C=0.5, l2)',
    fairness_adjusted: true,
    top_driver: 'Education Level (-0.18)',
    reasons: '',
    status: 'En attente',
  },
  {
    timestamp: '2026-05-14T11:15:33',
    filename: 'cv8.txt',
    name: 'James Müller',
    target_role: 'Operations Manager',
    stage: 'hard_filter',
    label: 'Reject',
    confidence: 0,
    model_name: 'N/A',
    fairness_adjusted: false,
    top_driver: 'N/A',
    reasons: 'Missing required language: French; Insufficient experience',
    status: 'Refusé',
  },
  {
    timestamp: '2026-05-13T16:20:45',
    filename: 'cv9.txt',
    name: 'Léa Moreau',
    target_role: 'Senior Data Analyst',
    stage: 'ml_model',
    label: 'Invite',
    confidence: 87.2,
    model_name: 'Logistic Regression (C=1.0, l1)',
    fairness_adjusted: true,
    top_driver: 'Education Level (+0.42)',
    reasons: '',
    status: 'Entretien planifié',
  },
  {
    timestamp: '2026-05-13T15:45:12',
    filename: 'cv10.txt',
    name: 'Karim Benali',
    target_role: 'Financial Controller',
    stage: 'ml_model',
    label: 'Invite',
    confidence: 91.5,
    model_name: 'Logistic Regression (C=1.0, l1)',
    fairness_adjusted: true,
    top_driver: 'Years of Experience (+0.48)',
    reasons: '',
    status: 'Embauché',
  },
  {
    timestamp: '2026-05-13T14:30:00',
    filename: 'cv11.txt',
    name: 'Emma Johnson',
    target_role: 'Marketing Manager',
    stage: 'ml_model',
    label: 'Reject',
    confidence: 45.3,
    model_name: 'Logistic Regression (C=0.5, l2)',
    fairness_adjusted: true,
    top_driver: 'Management Experience (-0.22)',
    reasons: '',
    status: 'Refusé',
  },
  {
    timestamp: '2026-05-13T10:12:30',
    filename: 'cv12.txt',
    name: 'Lucas Petit',
    target_role: 'Junior Analyst',
    stage: 'ml_model',
    label: 'Invite',
    confidence: 73.8,
    model_name: 'Logistic Regression (C=1.0, l1)',
    fairness_adjusted: true,
    top_driver: 'Extra Skills (+0.19)',
    reasons: '',
    status: 'En attente',
  },
  {
    timestamp: '2026-05-12T09:45:00',
    filename: 'cv13.txt',
    name: 'Clara Fischer',
    target_role: 'Software Engineering Lead',
    stage: 'ml_model',
    label: 'Reject',
    confidence: 52.1,
    model_name: 'Logistic Regression (C=0.5, l2)',
    fairness_adjusted: false,
    top_driver: 'Years of Experience (-0.31)',
    reasons: '',
    status: 'En attente',
  },
  {
    timestamp: '2026-05-12T08:30:00',
    filename: 'cv14.txt',
    name: 'Ahmed Rami',
    target_role: 'Operations Manager',
    stage: 'ml_model',
    label: 'Invite',
    confidence: 82.6,
    model_name: 'Logistic Regression (C=1.0, l1)',
    fairness_adjusted: true,
    top_driver: 'Management Experience (+0.35)',
    reasons: '',
    status: 'Entretien planifié',
  },
  {
    timestamp: '2026-05-11T17:20:15',
    filename: 'cv15.txt',
    name: 'Isabelle Nguyen',
    target_role: 'Senior Data Analyst',
    stage: 'ml_model',
    label: 'Invite',
    confidence: 76.4,
    model_name: 'Logistic Regression (C=1.0, l1)',
    fairness_adjusted: true,
    top_driver: 'International Experience (+0.28)',
    reasons: '',
    status: 'En attente',
  },
  {
    timestamp: '2026-05-11T14:10:45',
    filename: 'cv16.txt',
    name: 'Maxime Brun',
    target_role: 'Financial Controller',
    stage: 'hard_filter',
    label: 'Reject',
    confidence: 0,
    model_name: 'N/A',
    fairness_adjusted: false,
    top_driver: 'N/A',
    reasons: 'Missing required certification; Insufficient experience',
    status: 'Refusé',
  },
  {
    timestamp: '2026-05-11T11:05:00',
    filename: 'cv17.txt',
    name: 'Julia Costa',
    target_role: 'Marketing Manager',
    stage: 'ml_model',
    label: 'Invite',
    confidence: 69.7,
    model_name: 'Logistic Regression (C=1.0, l1)',
    fairness_adjusted: true,
    top_driver: 'International Experience (+0.25)',
    reasons: '',
    status: 'Entretien planifié',
  },
  {
    timestamp: '2026-05-10T16:40:30',
    filename: 'cv18.txt',
    name: 'Hugo Laurent',
    target_role: 'Junior Analyst',
    stage: 'ml_model',
    label: 'Reject',
    confidence: 38.5,
    model_name: 'Logistic Regression (C=0.5, l2)',
    fairness_adjusted: false,
    top_driver: 'Education Level (-0.15)',
    reasons: 'Insufficient education level',
    status: 'Refusé',
  },
];

export const MOCK_FAIRNESS_TREND: FairnessTrendPoint[] = [
  { date: '2026-05-10', epd: 12.4, rid: 0.68, delta_tpr: 6.8, composite_score: 42 },
  { date: '2026-05-11', epd: 9.8, rid: 0.74, delta_tpr: 5.2, composite_score: 55 },
  { date: '2026-05-12', epd: 6.5, rid: 0.82, delta_tpr: 3.9, composite_score: 68 },
  { date: '2026-05-13', epd: 4.2, rid: 0.89, delta_tpr: 2.4, composite_score: 78 },
  { date: '2026-05-14', epd: 2.1, rid: 0.956, delta_tpr: 1.3, composite_score: 89 },
];
